# Generated by Django 3.1.3 on 2020-11-09 14:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
